
class InvalidDataException(Exception):
    pass

class ProcessingException(Exception):
    pass

try:
    raise InvalidDataException('рядовой Райн')
except InvalidDataException as exc:
    print(f'поймано исключение {exc}')
    raise ProcessingException('это конец')
